# Generated by Django 6.0.3 on 2026-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('codigo_estudiante', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tarde', 'Tarde')], max_length=10)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha', 'nombre_estudiante'],
            },
        ),
    ]
