# Generated by Django 6.0.3 on 2026-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('codigo_estudiante', models.CharField(max_length=20)),
                ('tipo_solicitud', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
            ],
            options={
                'ordering': ['-fecha_solicitud', 'nombre_estudiante'],
            },
        ),
    ]
